#!/usr/bin/env bash

source ./clrconv

case $1 in
rgb2frgb)
  echo "Input: 128 255 64"
  ret=$(rgb2frgb "128" "255" "64")
  echo "Output: $ret"
  ;;

frgb2rgb)
  echo "Input: 0.5 1 0.25"
  ret=$(frgb2rgb "0.5" "1" "0.25")
  echo "Output: $ret"
  ;;

hex2rgb)
  echo "Input: #FF8000"
  ret=$(hex2rgb "#FF8000")
  echo "Output: $ret"
  ;;

rgb2hex)
  echo "Input: 255 128 0"
  ret=$(rgb2hex "255" "128" "0")
  echo "Output: $ret"
  ;;

rgb2hsl)
  echo "Input: 240 128 10"
  ret=$(rgb2hsl "240" "128" "10")
  echo "Output: $ret"
  ;;
esac
