#!/usr/bin/env bash

help_fn() {
  printf "> test [TEST] [VALUES]\n"
  printf "  --------------------------------------\n"
  printf "  TEST -> Color Convertion Function\n"
  printf "  VALUES -> String in quotes with Values\n"
  printf "            for the Functions (optional)\n"
  printf "            Will use predefined values\n"
  printf "            If left empty.\n"
  printf "  --------------------------------------\n"
  printf "  options -> rgb2frgb\n"
  printf "          -> frgb2rgb\n"
  printf "          -> hex2rgb\n"
  printf "          -> rgb2hex\n"
  printf "          -> hsl2rgb\n"
  printf "          -> rgb2hsl\n"
  printf "\n"
}

source ./colorconv.sh

case $1 in
all) ;;
rgb2frgb)
  echo "Input: 128 255 64"
  ret=$(rgb2frgb "128 255 64")
  echo "Output: $ret"
  ;;

frgb2rgb)
  echo "Input: 0.5 1 0.25"
  ret=$(frgb2rgb "0.5 1 0.25")
  echo "Output: $ret"
  ;;

hex2rgb)
  echo "Input: #FF8000"
  ret=$(hex2rgb "#FF8000")
  echo "Output: $ret"
  ;;

rgb2hex)
  echo "Input: 255 128 0"
  ret=$(rgb2hex "255 128 0")
  echo "Output: $ret"
  ;;

hsl2rgb)
  echo "Input: 31 88 49"
  ret=$(hsl2rgb "31 88 49")
  echo "Output: $ret"
  ;;

rgb2hsl)
  echo "Input: 240 128 10"
  ret=$(rgb2hsl "240 128 10")
  echo "Output: $ret"
  ;;

--help)
  help_fn
  exit 1
  ;;

-h)
  help_fn
  exit 1
  ;;

*)
  help_fn
  exit 1
  ;;
esac
